-- Feature 1: Maintenance Jobs & Technician Matching

-- Technicians directory
CREATE TABLE IF NOT EXISTS tecnicos (
  id_tecnico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT,
  telefone TEXT,
  especialidades TEXT[] DEFAULT '{}',
  estado_disponibilidade TEXT NOT NULL DEFAULT 'disponivel' CHECK (estado_disponibilidade IN (
    'disponivel', 'ocupado', 'indisponivel'
  )),
  avaliacao_media NUMERIC(3, 2) DEFAULT 0,
  total_trabalhos_concluidos INT DEFAULT 0,
  zona TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on tecnicos
ALTER TABLE tecnicos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated to select tecnicos" ON tecnicos
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow authenticated to insert tecnicos" ON tecnicos
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow authenticated to update tecnicos" ON tecnicos
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Allow authenticated to delete tecnicos" ON tecnicos
  FOR DELETE TO authenticated USING (true);

-- Maintenance job postings
CREATE TABLE IF NOT EXISTS trabalhos_manutencao (
  id_trabalho BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_condominio BIGINT NOT NULL REFERENCES condominios(id_comdominio) ON DELETE CASCADE,
  titulo TEXT NOT NULL,
  descricao TEXT,
  categoria TEXT NOT NULL CHECK (categoria IN (
    'canalização', 'eletricidade', 'serralharia', 'pintura', 'avac', 'geral'
  )),
  urgencia TEXT NOT NULL DEFAULT 'media' CHECK (urgencia IN ('critica', 'alta', 'media', 'baixa')),
  estado TEXT NOT NULL DEFAULT 'aberto' CHECK (estado IN (
    'aberto', 'atribuido', 'em_progresso', 'concluido', 'cancelado'
  )),
  created_by TEXT,
  id_tecnico_atribuido BIGINT REFERENCES tecnicos(id_tecnico) ON DELETE SET NULL,
  id_ocorrencia BIGINT REFERENCES ocorrencias(id_ocorrencia) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE
);

-- Enable RLS on trabalhos_manutencao
ALTER TABLE trabalhos_manutencao ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated to select trabalhos" ON trabalhos_manutencao
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow authenticated to insert trabalhos" ON trabalhos_manutencao
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow authenticated to update trabalhos" ON trabalhos_manutencao
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Allow authenticated to delete trabalhos" ON trabalhos_manutencao
  FOR DELETE TO authenticated USING (true);

-- Auto-update trigger for trabalhos
DROP TRIGGER IF EXISTS update_trabalhos_updated_at ON trabalhos_manutencao;
CREATE TRIGGER update_trabalhos_updated_at
  BEFORE UPDATE ON trabalhos_manutencao
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- Technician applications/proposals for jobs
CREATE TABLE IF NOT EXISTS candidaturas_trabalho (
  id_candidatura BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_trabalho BIGINT NOT NULL REFERENCES trabalhos_manutencao(id_trabalho) ON DELETE CASCADE,
  id_tecnico BIGINT NOT NULL REFERENCES tecnicos(id_tecnico) ON DELETE CASCADE,
  preco_proposto NUMERIC(10, 2),
  mensagem TEXT,
  estado TEXT NOT NULL DEFAULT 'pendente' CHECK (estado IN ('pendente', 'aceite', 'rejeitado')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on candidaturas
ALTER TABLE candidaturas_trabalho ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated to select candidaturas" ON candidaturas_trabalho
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow authenticated to insert candidaturas" ON candidaturas_trabalho
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow authenticated to update candidaturas" ON candidaturas_trabalho
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Allow authenticated to delete candidaturas" ON candidaturas_trabalho
  FOR DELETE TO authenticated USING (true);

-- Add FK from ocorrencias to trabalhos_manutencao (deferred since we created ocorrencias first)
ALTER TABLE ocorrencias
  DROP CONSTRAINT IF EXISTS ocorrencias_id_trabalho_fkey,
  ADD CONSTRAINT ocorrencias_id_trabalho_fkey
    FOREIGN KEY (id_trabalho_manutencao) REFERENCES trabalhos_manutencao(id_trabalho) ON DELETE SET NULL;
