-- Feature 2: Occurrence/Issue Tracking table
CREATE TABLE IF NOT EXISTS ocorrencias (
  id_ocorrencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_condominio BIGINT NOT NULL REFERENCES condominios(id_comdominio) ON DELETE CASCADE,
  titulo TEXT NOT NULL,
  descricao TEXT,
  categoria TEXT NOT NULL CHECK (categoria IN (
    'estrutural', 'canalização', 'eletricidade', 'elevador',
    'zona_comum', 'seguranca_incendio', 'outro'
  )),
  responsabilidade TEXT NOT NULL CHECK (responsabilidade IN ('condominio', 'fracao')),
  prioridade TEXT NOT NULL DEFAULT 'media' CHECK (prioridade IN ('critica', 'alta', 'media', 'baixa')),
  estado TEXT NOT NULL DEFAULT 'reportada' CHECK (estado IN (
    'reportada', 'triagem', 'em_progresso', 'resolvida', 'fechada'
  )),
  reportado_por TEXT,
  id_trabalho_manutencao BIGINT,
  notas TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  resolved_at TIMESTAMP WITH TIME ZONE
);

-- Enable RLS
ALTER TABLE ocorrencias ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated to select ocorrencias" ON ocorrencias
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow authenticated to insert ocorrencias" ON ocorrencias
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow authenticated to update ocorrencias" ON ocorrencias
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Allow authenticated to delete ocorrencias" ON ocorrencias
  FOR DELETE TO authenticated USING (true);

-- Auto-update trigger
DROP TRIGGER IF EXISTS update_ocorrencias_updated_at ON ocorrencias;
CREATE TRIGGER update_ocorrencias_updated_at
  BEFORE UPDATE ON ocorrencias
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
